services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=host.docker.internal;port=3306;database=proyectobiblioteca;user id=root;password=ContraseÑa12